name: Challange1
on: 
    workflow_dispatch:

jobs:
  job1:
    name: Printing Details
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run:
            date
            pwd
            ls -la


