name: pythonworkflow
on: workflow_dispatch

jobs:
  job1:
    name: data_pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  job2:
    name: Python Setup
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: check python version
        run: python --version

      - name: set up pandas
        run: pip install pandas  
        
      - name: clean_data
        run: |
          pwd
          ls -al
          pwd
          cd ModelCleaning
          pip install pandas
          python Cleandata.py
          ls -al

      - name: train_test_dataset
        run: |
          pip install scikit-learn joblib
          python ModelCleaning/train_test_dataset.py
